// types/index.ts
// Central export for all type definitions

// API Types
export type {
  ApiResponse,
  PaginatedResponse,
  ApiError,
  RouteContext,
  IdRouteParams,
  UidRouteParams,
  TokenRouteParams,
  VenueRouteParams,
  PlayerIdRouteParams,
  SearchParams,
  CreatePlayerRequest,
  UpdatePlayerRequest,
  BatchPlayerUpdate,
  CreateTournamentRequest,
  UpdateTournamentRequest,
  AssignBadgeRequest,
  PlayerSearchResult,
  VenueStats,
  PlayerStats,
  QuarterlyRanking,
  TimerState,
  CatchError,
  JsonValue,
  DynamicObject,
  Nullable,
} from './api';

export {
  isError,
  isPrismaError,
  getErrorMessage,
} from './api';

// Database Types
export type {
  Player,
  Badge,
  PlayerBadge,
  PokerTournament,
  TournamentDraft,
  TournamentDraftPlayer,
  ProcessedFile,
  PasswordReset,
  BonusPoints,
  PlayerWithBadges,
  PlayerWithAllRelations,
  TournamentDraftWithPlayers,
  TournamentDraftPlayerWithTournament,
  PlayerBadgeWithDetails,
  BadgeWithPlayers,
  PlayerBasicInfo,
  PlayerPublicInfo,
  TournamentBasicInfo,
  PlayerCreateInput,
  PlayerUpdateInput,
  TournamentDraftCreateInput,
  TournamentDraftUpdateInput,
  TournamentDraftPlayerCreateInput,
  TournamentDraftPlayerUpdateInput,
  BadgeCreateInput,
  PlayerBadgeCreateInput,
  PlayerWhereInput,
  TournamentDraftWhereInput,
  TournamentDraftPlayerWhereInput,
  BadgeWhereInput,
  PlayerBadgeWhereInput,
  PlayerOrderByInput,
  TournamentDraftOrderByInput,
  BadgeOrderByInput,
  QueryOptions,
  PrismaTransaction,
  RawQueryResult,
  TournamentStats,
  PlayerPerformance,
  VenueStatistics,
  BadgeEarningStats,
  QuarterlyPerformance,
  LeaderboardEntry,
  GameSummary,
  PlayerActivity,
} from './database';

export {
  Status,
  TournamentDraftStatus,
  PlayerAddedBy,
} from './database';

// Socket Types
export type {
  RealtimePlayer,
  RealtimeTournament,
  RealtimeTimerState,
  TournamentGameState,
  PlayerUpdatePayload,
  TournamentUpdatePayload,
  TimerUpdatePayload,
  BatchPlayerUpdatePayload,
  PlayerKnockoutPayload,
  CheckInPayload,
  SocketErrorPayload,
  RoomPayload,
  ServerToClientEvents,
  ClientToServerEvents,
  InterServerEvents,
  SocketData,
  TypedServer,
  TypedSocket,
  SocketCallback,
} from './socket';

export { SocketRooms } from './socket';

// Component Types
export type {
  TournamentPlayer,
  BadgeDisplay,
  PlayerProfile,
  TournamentDisplay,
  RankingEntry,
  ModalProps,
  BadgeModalProps,
  PlayerAvatarModalProps,
  TimerProps,
  BlindLevel,
  PlayerRowProps,
  CheckInModalProps,
  StatCardData,
  ChartDataPoint,
  TableColumn,
  SortState,
  PaginationState,
  FilterState,
  SearchState,
  LoadingState,
  ToastNotification,
  FieldError,
  FormState,
  SelectOption,
  PlayerSearchOption,
  VenueOption,
  QuarterOption,
  DateRange,
  GameViewData,
  ColorTheme,
  RarityTier,
  BadgeCategory,
} from './components';

// Re-export commonly used Prisma types for convenience
export { Prisma } from '@prisma/client';
